"""F5.1: chat_messages.model_used

Revision ID: 62a297614fbd
Revises: f9d39fbbfe5e
Create Date: 2026-06-25 17:51:36.540973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62a297614fbd'
down_revision: Union[str, Sequence[str], None] = 'f9d39fbbfe5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'model_used')
    # ### end Alembic commands ###
