"""M2.4: agent_contexts.telos

Revision ID: 7b552996348d
Revises: d4c01f1e2e49
Create Date: 2026-06-25 21:42:42.285105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b552996348d'
down_revision: Union[str, Sequence[str], None] = 'd4c01f1e2e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default '' so existing rows satisfy NOT NULL; then drop it so the column
    # matches the model (the app always supplies a value).
    op.add_column('agent_contexts', sa.Column('telos', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default=''))
    op.alter_column('agent_contexts', 'telos', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_contexts', 'telos')
    # ### end Alembic commands ###
